### PR TITLE
Bug fixes & Node Improvements

### PR DESCRIPTION
**Pull request by ohkaiby**
## Bugfixes
* OAuth module was being instantiated with improper parameters.
* Data module was mislabeling its `parseUrl()` function.

## ES6 Modules
* `forcejs` was not building properly with webpack when `exclude: [/node_modules/]` (a best practice) was included in the webpack config’s loaders. This is because NodeJS can’t natively parse ES6 import/export statements. We are now using Webpack to build the source files.

* New import syntax:
```
import { oauth, data } from 'forcejs';

oauth.createInstance(); // ...
data.createInstance(); // ...
```

### CODE REVIEW

**Comment by ccoenraets** [comment]
@ohkaiby Couple of comments/questions.
- Thanks for catching createInstance init parameters mismatch
- Thanks for catching the parseURL error
- People have asked to decouple the oauth workflow module and service call module, which is why I refactored the library so that you can import "submodules" separately (without pulling the whole thing if you only need one submodule). In the future there may be more submodules. I'm concerned that (with most build tools) using force.js as a facade where all the submodules are imported will pull all the submodules even if you only need one. Thoughts?
- Right now the core use case for forcejs is to run client-side (plain client-side JS app or Codova), not to run server-side (Node). Does your specific CommonJS setup work in that context? I wasn't immediately able to run/build for that use case. If it does, could you update the Quick Start steps in readme.md to show how to build and run a minimalistic client-side JS app?
Thanks,
Christophe

**Comment by ohkaiby** [comment]
@ccoenraets 

Thanks for the comments; will take a look at making sure submodules can be imported separately.

As for client-side vs server-side, I actually am using forcejs on the client-side only; I'll update the README instructions.

**Comment by ohkaiby** [comment]
@ccoenraets You were right about submodules not being able to be standalone in this update.

I've updated the file structure so that once again the submodules can be used standalone (the way they were before this update).

I've also allowed for the ability to use the newer ES6 import syntax.

I've also created a `dist/` folder for those who want to just include the libraries as standalone files (like in `<script></script>`) tags.

The README now reflects these changes as well. Let me know if there's anything else that needs to be changed!

**Comment by ccoenraets** [comment]
@ohkaiby Thanks for the changes. Looking good. Tried both es5 and es6, and it works fine. 
Final thoughts:
- Could you change the global vars that get created in the es5 scenario from oauth and data to forceOauth and forceData to reduce the risk of name collisions (probably means changing the file names as well)
- What do you think about changing force.js to export OAuth and Data instead of oauth and data (to stick to the factory/static method kind of naming convention I use elsewhere). i.e: var oauth = Force.OAuth.createInstance(); similar to var oauth = OAuth.createInstance() when using the direct submodule import we show in the quick start.

**Comment by ohkaiby** [comment]
@ccoenraets 

I agree with both changes and I've made the necessary updates.

**Comment by ccoenraets** [comment]
Thanks @ohkaiby. Merged.

**Pull request merged**
