### PR TITLE
make token store settable

### PR DESCRIPTION
**Pull request by dcarroll**
Need to make the token store part of the params so that I can pass in a
store and later get to the values of the store.

Also added a promise to the init function to chain from.

`force.init({params}).then(() force.login());`

### CODE REVIEW

**Comment by ccoenraets** [comment]
- init() is a synchronous function. Worried that by returning a promise, people would make wrong assumptions about what it does and infer some async processing. 
- You can pass the accessToken in init. tokenStore used to be settable, but this option was removed for security reason to prevent developers from storing access tokens in insecure stores (like localStorage). How about an init param that lets you choose between approved stores: memory (default) or sessionStorage?

**Comment by dcarroll** [comment]
Ok, I don't really care about the promise.

But what I do need for lightning out is to get the oauth token from memory.   How does storage session work?

**Comment by ccoenraets** [comment]
The access token is stored in the oauth object which is currently not exposed publicly. What if I add a getAccessToken() function? Would that meet your requirement?

**Comment by ccoenraets** [comment]
Just pushed 0.7.3 with added getAccessToken() function. Also published to npm. Let me know if that  works for your use case.

**Comment by dcarroll** [comment]
I also need the instance url!  :-)


On Tue, Oct 27, 2015 at 1:53 PM, Christophe Coenraets <
notifications@github.com> wrote:

> Just pushed 0.7.3 with added getAccessToken() function. Also published to
> npm. Let me know if that works for your use case.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ccoenraets/forcejs/pull/6#issuecomment-151640328>.
>



-- 
Thanks,
Dave

**Comment by dcarroll** [comment]
This works:
/**
 * Gets the instance_url (if logged in)
 * @returns {string} | undefined
 */
export let getInstanceUrl = () => (oauth) ? oauth.instance_url : undefined;



On Tue, Oct 27, 2015 at 2:11 PM, Dave Carroll <dcarroll@salesforce.com>
wrote:

> I also need the instance url!  :-)
>
>
> On Tue, Oct 27, 2015 at 1:53 PM, Christophe Coenraets <
> notifications@github.com> wrote:
>
>> Just pushed 0.7.3 with added getAccessToken() function. Also published to
>> npm. Let me know if that works for your use case.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ccoenraets/forcejs/pull/6#issuecomment-151640328>.
>>
>
>
>
> --
> Thanks,
> Dave
>



-- 
Thanks,
Dave

**Comment by ccoenraets** [comment]
Pushed 0.4. added getOAuthResult() function. returns an object with all the params returned as part of the OAuth callback. Removed getAccessToken() since access_token is a param of the object returned by getOAuthResult().

**Comment by ccoenraets** [comment]
I meant pushed 0.7.4

**Comment by dcarroll** [comment]
Ah, that's super flexible then!  Thanks!


On Tue, Oct 27, 2015 at 2:26 PM, Christophe Coenraets <
notifications@github.com> wrote:

> I meant pushed 0.7.4
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ccoenraets/forcejs/pull/6#issuecomment-151649444>.
>



-- 
Thanks,
Dave

**Pull request closed without merging**
